<section class="my-code">
    <h1>async await</h1>
    <p>
      Large promise chaining example is too complex. so the easy way is using async and await.      
    </p>
    <code>
        function greet(ms){
            return new Promise((resolve, reject) => {
                if(ms < 500){
                    reject(`Value must be greater then 500`);
                }
                setTimeout(() => resolve(`Done for ${ms} ms`), ms)
            });
        }

        greet(1000)
        .then(res => {console.log(res); return greet(1200);})
        .then(res => {console.log(res); return greet(1300);})
        .then(res => {console.log(res); return greet(1400);})
        .then(res => {console.log(res); return greet(1500);})

        async function start(){
            const res_1 = await greet(1000);
            console.log(res_1);

            const res_2 = await greet(1200);
            console.log(res_2);

            const res_3 = await greet(1300);
            console.log(res_3);

            const res_4 = await greet(1400);
            console.log(res_4);
        }
        start();
    </code>
    <console>
        
    </console>
</section>

<section class="my-code">
    <h1>async await - Error Handling</h1>
    <p>
       
    </p>
    <code>
        function greet(ms){
            return new Promise((resolve, reject) => {
                if(ms < 500){
                    reject(`Value must be greater then 500`);
                }
                setTimeout(() => resolve(`Done for ${ms} ms`), ms)
            });
        }

        async function start(){
            try{
                const res_1 = await greet(1000);
                console.log(res_1);

                const res_2 = await greet(400);
                console.log(res_2);

                const res_3 = await greet(1300);
                console.log(res_3);

                const res_4 = await greet(1400);
                console.log(res_4);

                return {msg : "completed successfully!"}
            }catch(err){
                throw err;
            }            
        }
        start()
        .then(res => {console.log(res)})
        .catch(err => {console.log(err)});
    </code>
    <console>
        PromiseÂ {<pending>}
        Done for 1000 ms
        Value must be greater then 500
    </console>
</section>